# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Beta distribution to firebase App Distribution"
  lane :beta do |options|
      if not options[:no_build_increase]
          increment_build_number
      end
      build_ios_app(scheme: "Bap", export_method: "ad-hoc")
      firebase_app_distribution(
      	app: "1:243916283099:ios:f32ce10f18c4f8fe5640fe",
      	groups: "Default",
      	release_notes: "Distributed with fastlane",
      	firebase_cli_token: ENV["FIREBASE_TOKEN"])
  end
end
